### ISSUE TITLE
could you add functionality to use lower constraint vector fo G matrix

### ISSUE THREAD

**Issue by k-maheshkumar** [stephane-caron/qpsolvers#1]
hi,
I am trying to use your code as interface to test my optimization problem with mutli qp solvers.
From your code I can see that it supports the following problem
  

        minimize (1/2) * x.T * P * x + q.T * x
        subject to
            G * x <= h
            A * x == b

where you set the h vector  as upper limit for matrix G, but I have a problem of following format,

        minimize (1/2) * x.T * P * x + q.T * x
        subject to
            l <= G * x <= h
            A * x == b
            with lx<= x <= ux

Can you please add the functionality to support the lower limit vector for the G matrix. Also lower and upper bounds for x.

**Comment by stephane-caron** [comment]
Hi,

You can set your lower limits using the format `G * x <= h`:

- For `l <= G * x`, just write `-G * x <= -l`
- For `x <= ux` just write `eye(n) * x <= ux` where `n = len(x)`
- Idem for `lx <= x`

Some solvers indeed accept bounds in zonotope form (`lx <= x <= ux`) because they can deal with it faster, but it is not the case for all solvers here. For now, I will stick to the current API, but if you want to extend the API with some automatic conversions from the zonotope form I will gladly merge the PR ;-)

**Comment by k-maheshkumar** [comment]
Thanks for the reply and it would be great if you can extend the api for the auto conversion of the constraints.

**Comment by k-maheshkumar** [comment]
Actually, what you have just said is a nice trick. Thanks for the suggestions. 

Also, I don't understand what you mean by Idem for lx <= x. Can you please tell me what is that.

**Comment by stephane-caron** [comment]
Sure. I meant a combination of the two options above:

- For `lx <= x`, just write `-eye(n) * x <= -lx`

**Comment by k-maheshkumar** [comment]
Ok thank you. :)
