### ISSUE TITLE
Problem about the hypercube bounds

### ISSUE THREAD

**Issue by cjfcsjt** [stephane-caron/qpsolvers#13]
Hi, I have a problem about setting the box bounds
I saw the related issue, and know that I can use the trick -Gx<-h
However, the api only allow one G matrix to pass, but I want to bound x using -G1x<h1, G2x<h2
I don't know how to do this.(I want to implement -1<x<1 )
I also saw that gpoases support for the case. However, when I run:
"x = solve_qp(p,q,G,h,A,b,solver='qpoases')"
it tell me:
"ImportError: qpOASES not found"

**Comment by stephane-caron** [comment]
> However, the api only allow one G matrix to pass, but I want to bound x using -G1x<h1, G2x<h2

Multiple inequalities are obtained by stacking the corresponding matrices and vectors. In your example, you can define ``G = vstack([G1, -G2])`` and ``h = hstack([h1, h2])``, and you are back to the ``-G * x <= -h`` case.

> However, when I run ``x = solve_qp(p,q,G,h,A,b,solver='qpoases')`` it tell me: "ImportError: qpOASES not found"

This is because the qpOASES Python module is not installed on your machine. Check out the [official installation page](https://projects.coin-or.org/qpOASES/wiki/QpoasesInstallation) for instructions.

At the time I installed it, there were a couple of things to do to make the ``make python`` step work. You can download qpOASES from [this repository](https://github.com/stephane-caron/qpOASES), or check out its 4-5 last commits to see how to cope with these issues.
