### ISSUE TITLE
solver running time is too long

### ISSUE THREAD

**Issue by xing-shuai** [stephane-caron/qpsolvers#15]
I got a very huge matrix P which has 10k+ dimentions.
The solving process takes a lot of time for cvxopt and any other solvers.
So, do I have any way to accelerate the solving process? 
Another question is:
when using the default solver with a large matrix P(since it has a vary high dim,determinant of P is very close to zero, e.g. 5..e-324. when increasing the dimension of P, the determinant of P is 0.0, but it is not, the precision of numpy double reachs to the limit), I got the error "G is not a positive definite matrix", while cvxopt does not report this error.

**Comment by stephane-caron** [comment]
CVXOPT is a dense solver, these are well-suited to high-dimensional problems. You should try using a sparse solver (OSQP, ECOS, ...). The [sparse problem example](https://github.com/stephane-caron/qpsolvers/blob/master/examples/sparse_problem.py) shows you how to use them.

Make sure you use SciPy sparse matrices rather than NumPy arrays when building your problem matrices for these solvers.

**Comment by mohitsrinivasan** [comment]
Hi,

I am getting an error called "ValueError: Buffer has wrong number of dimensions (expected 1, got 2). I don't think there is anything wrong in the way I am declaring my QP. Do you think I am missing something really minor?

Thanks a lot!

Best,
Mohit

**Comment by stephane-caron** [comment]
Closing this issue now. Feel free to re-open if you have further questions.
