### ISSUE TITLE
TypeError: argument of type 'ValueError' is not iterable

### ISSUE THREAD

**Issue by Ing-David** [stephane-caron/qpsolvers#25]
Hello, I have problem with solve_qp when I want to run the following code:

from qpsolvers import solve_qp
P = np.array([4.,5.,5.,8.]).reshape(2,2)
q = np.array([-3.,2.]).reshape(1,2)[0]
G = np.array([1,1,-2,-3,1,0,0,1,-1,0,0,-1]).reshape(6,2)
h = np.array([2400.,-1100.,1200.,1500.,-300.,0.])
A = None
b = None
sol = solve_qp(P,q,G,h,A,b,solver='quadprog')

I got this error:
sol = solve_qp(P,q,G,h,A,b,solver='quadprog')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qpsolvers/__init__.py", line 262, in solve_qp
    return quadprog_solve_qp(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qpsolvers/quadprog_.py", line 90, in quadprog_solve_qp
    if "matrix G is not positive definite" in e:
TypeError: argument of type 'ValueError' is not iterable

**Comment by stephane-caron** [comment]
Running your example after @rimaddo's fix, we get:
```python
ValueError: Buffer dtype mismatch, expected 'double' but got 'long'
```
The reason for this is that all entries in your `G` matrix are integers, so numpy defins its internal type as `long` instead of `double`. You can fix this by either:
```python
# adding a decimal mark to any entry of G
G = np.array([1., 1, -2, -3, 1, 0., 0, 1, -1, 0, 0, -1]).reshape(6,2)

# specifying the type afterwards
G = np.array([1, 1, -2, -3, 1, 0, 0, 1, -1, 0, 0, -1]).reshape(6,2).astype(float)
```
When you have a numpy matrix, you can always check its type in ``G.dtype``. With your code, `G.dtype` was `int64`. After the proper change, you should see it switch to `float64`:
```python
In [41]: G.dtype
Out[41]: dtype('float64')

In [42]: solve_qp(P, q, G, h, A, b, solver='quadprog')
Out[42]: array([300.        , 166.66666667])
```

**Comment by angibenton** [comment]
Hi - apologies in advance as I am new to python.  I'm trying to verify the parameter types for solve_qp() by running this QP: 
![image](https://user-images.githubusercontent.com/56163800/100018875-25193a80-2dab-11eb-9df4-ba9a626d0355.png)
```

import qpsolvers as qp
import numpy as np

P = (-100) * np.identity(5).astype(float) #
q = np.array([42, 44, 45, 47, 47.5]).astype(float)
G = np.array([[20, 12, 11, 7, 4]]).astype(float)
h = np.array([40]).astype(float)
lb = np.zeros((5,)).astype(float)
ub = np.ones((5,)).astype(float)

x_star = qp.solve_qp(P = P, q = q, G = G, h = h, lb = lb, ub = ub)

print(x_star)

```
The arrays are dtype float64 have shapes: 

- P:  (5, 5)
- q:  (5,)
- G:  (1, 5)
- h:  (1,)
- lb:  (5,)
- ub:  (5,)

I get the following error:

  x_star = qp.solve_qp(P = P, q = q, G = G, h = h, lb = lb, ub = ub)
  File "/usr/local/lib/python3.8/site-packages/qpsolvers/__init__.py", line 262, in solve_qp
    return quadprog_solve_qp(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/qpsolvers/quadprog_.py", line 90, in quadprog_solve_qp
    if "matrix G is not positive definite" in e:
TypeError: argument of type 'ValueError' is not iterable

**Comment by nikolaif399** [comment]
Looks like this issue here is that your hessian matrix (P) is not positive definite which is a requirement for the quadprog algorithm. Quadprog uses the Goldfarb/Idnani algorithm under the hood which will only work for strictly convex quadratic programs which yours is not. For solving nonconvex QPs I would recommend trying OSQP instead.

**Comment by angibenton** [comment]
Oh I see - thank you so much.

**Comment by stephane-caron** [comment]
Note that OSQP is also designed for _convex_ quadratic programs (from the abstract of the [OSQP paper](https://web.stanford.edu/~boyd/papers/pdf/osqp.pdf): "We present a general-purpose solver for convex quadratic programs based on the alter-nating direction method of multipliers, ..."). It might work when the problem is not strictly convex, but here the problem of @angibenton is entirely concave.

All QP solvers wrapped so far in `qpsolvers` are designed for convex quadratic programs. (Thanks for bringing this point up! I just updated the README and doc accordingly :grinning:) There are algorithms available in the research for concave quadratic programs, for instance [this paper](http://www.optimization-online.org/DB_FILE/2018/08/6760.pdf) and references therein, but I don't see open source implementations available for Python.

@angibenton Alternatively you could go directly for a nonlinear optimization package such as [ipopt](https://pypi.org/project/ipopt/). I had a great experience with it using [CasADi](https://web.casadi.org/) to write the optimization problem symbolically (to use IPOPT directly one has to implement not only the objective function but also its derivatives, which is a bit tedious).

**Comment by stephane-caron** [comment]
@angibenton I just realized your question is not related to the original question of this issue. Next time open a new issue for each new question :slightly_smiling_face: This way we can continue each discussion thread independently.

**Comment by angibenton** [comment]
@stephane-caron I see that now - my apologies! I didn't realize that the "TypeError: argument of type 'ValueError' is not iterable" shows up for various unrelated issues. Thanks!
